#!/usr/bin/python
import os, sys

projectDir = os.path.join(os.path.dirname(__file__), "../pysrc/")
sys.path.append(projectDir)
sys.path.append(projectDir + "labstreaminglayer_ros/")

from nodes.labstreaminglayer_syncronizer import LabStreaminLayerSynchronizer

import rospy

if __name__ == '__main__':
    try:
        labStreaminLayerSynchronizer = LabStreaminLayerSynchronizer()

        labStreaminLayerSynchronizer.node()


    except rospy.ROSInterruptException:
        pass
